[build]
buildCommand = "npm install --include=dev && npm run server:build && cp -r server/data server_dist/data"

[deploy]
startCommand = "npx drizzle-kit push --force; npm run server:prod"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
