[build]
buildCommand = "npm install && npm run server:build && cp -r server/data server_dist/data"

[deploy]
startCommand = "npm run server:prod"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
